### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jeriox** [simulate-digital-rail/interlocking-exporter#2]
The polygon `52.295619711065676 13.26527953169716 52.295298190404885 13.267897367695696 52.310702311909544 13.272178173283464 52.310826940098465 13.270182609776388` crashes with the following error:

```
Traceback (most recent call last):
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\ui\app.py", line 53, in run_converter
    json.dump(exporter.export_placement(), placement_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\interlocking_exporter\exporter.py", line 261, in export_placement
    else get_edges_from_nodes(node, node.connected_on_right)[0]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by jeriox** [comment]
also happens for `52.40329600092247 12.971838712692263 52.403440005172996 12.968555688858034 52.42328191313818 12.972321510314943 52.42302020464885 12.97635555267334`

**Comment by jeriox** [comment]
also happens for `52.485197683636194 13.369739055633545 52.48452472795169 13.371863365173342 52.471207235143424 13.364310264587404 52.47118109282307 13.362207412719728`
